name: scuolabook
version: "3.3.0"
summary: Scuolabook
grade: stable
description: |
  Puoi leggere su computer desktop, sul portatile e sul tablet i tuoi libri scolastici digitali
confinement: strict
architectures:
  - build-on: amd64
  
environment:
  LD_LIBRARY_PATH: $SNAP/opt/scuolabook
  QTWEBENGINEPROCESS_PATH: $SNAP/opt/scuolabook/QtWebEngineProcess
  QSG_RENDER_LOOP: basic
  
apps:
  scuolabook:
    command: bin/desktop-launch $SNAP/opt/scuolabook/Scuolabook
    desktop: usr/share/applications/scuolabook.desktop
    plugs:
      - alsa
      - cups-control
      - desktop
      - desktop-legacy
      - home
      - opengl
      - gsettings
      - unity7
      - pulseaudio
      - removable-media
      - wayland
      - x11
      
parts:
  scuolabook:
    plugin: dump 
    source: https://cdn-support.scuolabook.it/3.3/Scuolabook_3.3.0_amd64_16.04.deb
    stage-packages:
      - libxslt1.1
      - gstreamer1.0-plugins-bad
      - libpulse0
      - libxrandr2
      - libegl1-mesa
      - libgl1-mesa-glx
      - libnss3
      - libqt5svg5
      - libqt5webkit5
      - libgdk-pixbuf2.0-0
      
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
